export const CHANGE_TAB = 'CHANGE_TAB';
export const CHANGE_EDIT_TITLE_TAB = 'CHANGE_EDIT_TITLE_TAB';
export const WIDE_SCREEN = 'WIDE_SCREEN';
export const CHANGE_TRAVEL_SCREEN = 'CHANGE_TRAVEL_SCREEN';
export const SET_NAVIGATOR = 'SET_NAVIGATOR';
export const SET_SCROLL_REF = 'SET_SCROLL_REF';
export const SET_SCREEN = 'SET_SCREEN';