export const RESET = 'RESET';

// photos
export const ADD_PHOTO = 'ADD_PHOTO';
export const UPDATE_PHOTO = 'UPDATE_PHOTO';
export const DELETE_PHOTO = 'DELETE_PHOTO';
export const DELETE_ALL_PHOTO = 'DELETE_ALL_PHOTO';
export const CHANGE_PHOTOS_ARRAY = 'CHANGE_PHOTOS_ARRAY';

export const ADD_PHOTO_WITH_NO_GPS = 'ADD_PHOTO_WITH_NO_GPS';
export const DELETE_PHOTO_WITH_NO_GPS = 'DELETE_PHOTO_WITH_NO_GPS';
export const DELETE_ALL_PHOTO_WITH_NO_GPS = 'DELETE_ALL_PHOTO_WITH_NO_GPS';
export const CHANGE_PHOTOS_WITH_NO_GPS_ARRAY = 'CHANGE_PHOTOS_WITH_NO_GPS_ARRAY';

// Map Position
export const UPDATE_CENTER = "UPDATE_CENTER";

// Map Style
export const SELECT_MAP_STYLE = 'SELECT_MAP_STYLE';

// Photo Style
export const SELECT_PHOTO_SHAPE = 'SELECT_PHOTO_SHAPE';
export const SELECT_PHOTO_OUTLINE_COLOR = 'SELECT_PHOTO_OUTLINE_COLOR';
export const SELECT_PHOTO_OUTLINE_WIDTH = 'SELECT_PHOTO_OUTLINE_WIDTH';

// Route line Style
export const SELECT_ROUTE_COLOR = 'SELECT_ROUTE_COLOR';
export const SELECT_ROUTE_WIDTH = 'SELECT_ROUTE_WIDTH';

// Map Title
export const SET_TITLE_TEXT = 'SET_TITLE_TEXT';
export const SELECT_TITLE_FONT = 'SELECT_TITLE_FONT';
export const SELECT_TITLE_ALIGN = 'SELECT_TITLE_ALIGN';
export const SELECT_TITLE_BG = 'SELECT_TITLE_BG';
export const SELECT_TITLE_COLOR = 'SELECT_TITLE_COLOR';
export const SET_TITLE_EDIT_MODE = 'SET_TITLE_EDIT_MODE';
export const SELECT_TITLE_X = 'SELECT_TITLE_X';
export const SELECT_TITLE_Y = 'SELECT_TITLE_Y';

export const SET_MAP_IMAGE_CAPTURE = 'SET_MAP_IMAGE_CAPTURE';
export const SET_TIMELINE_IMAGE_CAPTURE = 'SET_TIMELINE_IMAGE_CAPTURE';

// ETC
export const SET_LOCATION_TEXT = 'SET_LOCATION_TEXT';
export const SET_REMEMBER = 'SET_REMEMBER';
export const IMAGE_UPLOAD_PROGRESS = 'IMAGE_UPLOAD_PROGRESS';
export const IMAGE_UPLOAD_TOTAL = 'IMAGE_UPLOAD_TOTAL';